glo Data "../../data"
glo PrePeriod "${Data}/acs-pre-period"
glo Output "../../output"
glo Graphs "${Output}/graphs"
glo IndustryCrosswalks "${Data}/gdp_state_industry_BEA/145101-V2"
glo CapStock "${Data}/CapByState"